### ISSUE TITLE
Support for il merged assemblies?

### ISSUE THREAD

**Issue by eleung83** [NicolasPrats/DvBrowser#15] opened 2023-04-26 12:41 UTC
Does this support Il Merged assemblies?

I tried loading the debug version of my plugin assembly and seems to just stay at:

![image](https://user-images.githubusercontent.com/26326026/234577141-ffd6c9c2-6d91-46d0-b2f6-755797d45b02.png)

I thought about trying to point to another version of the same plugin assembly that isn't merged by ilmerge, but seems to also still get to the same state when loading in the app

**Comment by NicolasPrats** [comment] 2023-04-26 16:21
I have not tested, but theorically it should work with merged assemblies. However if you don't have a PDB file, you will not have the source code displayed in the debugger.
The loading plugins phasis can be long if you have a lot of steps in your organization (~90S on my biggest project).  How much time have you waited ?

**Comment by NicolasPrats** [comment] 2023-04-26 16:43
I have found a bug: if an error occurs during this phasis, it is not displayed. 
Can you please try with the [latest release](https://github.com/NicolasPrats/DvBrowser/releases/tag/V0.1.2.1)? It will probably still not work but at least, I hope you will know why.

**Comment by eleung83** [comment] 2023-04-26 17:26
ok, that helped to identify the root cause of the assembly loading issue:

![image](https://user-images.githubusercontent.com/26326026/234653846-612ef2a0-43f4-44bf-a3c9-a6366ee2f0d6.png)

Perhaps could apply a filter to exclude sdkmessageprocessingsteps which have impersonation setup, so that other plugin steps within the assembly could still be debugged?

**Comment by NicolasPrats** [comment] 2023-04-26 17:57
[This version](https://github.com/NicolasPrats/DvBrowser/releases/tag/V0.1.2.2) allows you to continue with other plugin steps. Ignored steps will not be executed at all,  the behavior of your application and of other steps may be affected.
Please tell me if that fix your issue.

**Comment by NicolasPrats** [comment] 2023-04-27 06:07
>  I would randomly guess the process is failing to try and load the dll from the location provided in the previous steps when running the app?

If without the debugger, you can see your plugins running, then all dll have been sucessfully loaded. 
Can you try to download the source code and run directly the browser from Visual Studio?  You should be able to see where Visual Studio stops to work. It may give an idea.

**Comment by NicolasPrats** [comment] 2023-04-28 05:57
I've tested with an ilmerged assembly and was not able to reproduce.

The error code 0x80131506 means "internal clr error" which may be caused by a bug in the .NET Framework. So another test you could do is to try on another computer with a fresh installation of Visual Studio and of .NET Framework.
If it's possible for you to provide me the source code of your plugin, I can try to reproduce on my side.

**Comment by NicolasPrats** [comment] 2023-05-04 09:58
>it would assume the debugger is attached, as I was debugging the browser application itself, rather than my plugin assembly

It's ok. Your plugin assembly is loaded by the browser application. If you can debug the browser application, you can debug your plugin assembly.
The easiest way is to put a breakpoint where your plugin will be executed [(method ``ExecuteStep`` of the class ``OrganizationServiceWithEmulatedPlugin``](https://github.com/NicolasPrats/DvBrowser/blob/main/Dataverse.Plugin.Emulator/Services/OrganizationServiceWithEmulatedPlugins.cs#L265)), then you step into the method ``plugin.Execute()``.
A more convenient way is to add your plugin project to the Dataverse Browser Solution (without modifying any project reference). Then you can add breakpoints directly in your code.

**Comment by NicolasPrats** [comment] 2023-05-18 19:57
Hi @eleung83 ,

Any progress? Did you manage to add breakpoints? Have you tested your plugin on another machine?

**Comment by ginow** [comment] 2023-05-19 13:24
Hi @eleung83 

Hope this may help you, I don't know whether your issue is due to ILMerge or not but there is a good alternative available to avoid using it:

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins

**Comment by eleung83** [comment] 2023-05-22 16:07
I've managed to get it to hit the breakpoint within my plugin assembly using the latest version and adding the plugin project into the same solution as the DvBrowser solution.

I haven't gone back to trying to point to the original plugin dll sitting within it's own separate project yet to see if this route still works

**Comment by NicolasPrats** [comment] 2023-05-23 07:26
I'm glad you succeeded in debugging your plugin.

Regarding the behavior when using directly the compiled version of the Dataverse Browser, given that I cannot reproduce and CLR internal error code is not very explicit, I am unable to help you :(.  So I'm going to close this issue.

If you get more information or can reproduce with a DLL you can share with me, I will be happy to continue to investigating this topic.

**Closed by NicolasPrats** 2023-05-23 07:26 UTC
Labels: question
